<?php
/**
 * Plugin Name: Events Calendar SEO Suite
 * Description: Adds noindex meta tags to past and paginated Events Calendar pages,
 *              and injects full Event schema markup (JSON-LD) on single event pages.
 * Version: 1.0.0
 * Author: Angelo Gabriel M. De Guzman
 * Text Domain: events-calendar-seo-suite
 *
 * ============================================================================
 * HOW TO USE THIS PLUGIN
 * ============================================================================
 *
 * 1. INSTALL
 *    Upload this file inside a .zip to:
 *    WP Admin -> Plugins -> Add New -> Upload Plugin -> Activate
 *
 *    Requires: The Events Calendar plugin (free version or Pro)
 *
 * 2. WHAT IT DOES AUTOMATICALLY (no configuration needed)
 *
 *    a) NOINDEX on paginated calendar views
 *       Pages like /events/month/, /events/week/, /events/list/ etc.
 *       generate infinite low-value URLs that hurt SEO. This plugin
 *       adds <meta name="robots" content="noindex, nofollow"> to all of them.
 *
 *    b) NOINDEX on past individual events
 *       Once an event's end date has passed, it adds:
 *       <meta name="robots" content="noindex, follow">
 *       Upcoming and active events remain fully indexable.
 *
 *    c) EVENT SCHEMA MARKUP (JSON-LD)
 *       Adds structured data on every single event page so Google can
 *       display rich results (event name, date, location, image).
 *       Works alongside Yoast SEO and RankMath without conflict.
 *
 * 3. COMPATIBILITY
 *    - Works with The Events Calendar (free) and Events Calendar Pro
 *    - Compatible with Yoast SEO, RankMath, and All-in-One SEO
 *    - No configuration required — activate and done
 *
 * ============================================================================
 * CUSTOMIZATION (optional)
 * ============================================================================
 *
 * To change which calendar URL patterns get noindexed, edit the
 * ecss_noindex_calendar_views() function below.
 *
 * To change the event attendance mode (e.g. online vs in-person),
 * edit the 'eventAttendanceMode' value inside ecss_event_schema().
 *
 * ============================================================================
 * TROUBLESHOOTING
 * ============================================================================
 *
 * Q: The schema is not showing on my event pages.
 * A: Make sure The Events Calendar is installed and activated.
 *    Check that tribe_get_start_date() and tribe_get_end_date() exist.
 *
 * Q: Past events are still being indexed.
 * A: It can take a few days for Google to re-crawl and update.
 *    You can also submit updated URLs via Google Search Console.
 *
 * Q: Will this conflict with Yoast SEO?
 * A: No. This plugin only adds noindex tags and JSON-LD schema.
 *    It does not touch Yoast's existing schema output.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

// =============================================================================
// PART 1: NOINDEX — PAGINATED CALENDAR VIEWS
// =============================================================================
/**
 * Adds noindex, nofollow to all paginated calendar view URLs.
 *
 * Targets these URL patterns (generated by The Events Calendar):
 *   /events/month/     <- Monthly calendar view
 *   /events/week/      <- Weekly calendar view
 *   /events/list/      <- List view
 *   /events/photo/     <- Photo view (Events Calendar Pro)
 *   /events/summary/   <- Summary view (Events Calendar Pro)
 *   ?eventDate=        <- Date-specific paginated URLs
 *
 * These pages paginate infinitely and add no unique SEO value.
 * Noindexing them keeps your crawl budget focused on real content.
 *
 * TO ADD MORE PATTERNS: Add another strpos() check below.
 * TO REMOVE A PATTERN:  Delete or comment out that check.
 */
add_action( 'wp_head', 'ecss_noindex_calendar_views', 1 );

function ecss_noindex_calendar_views() {
    $uri = isset( $_SERVER['REQUEST_URI'] ) ? $_SERVER['REQUEST_URI'] : '';

    $patterns = array(
        '/week/',        // Weekly view
        '/month/',       // Monthly view
        '/list/',        // List view
        '/photo/',       // Photo view (Pro)
        '/summary/',     // Summary view (Pro)
        'eventDate=',    // Paginated date parameter
    );

    foreach ( $patterns as $pattern ) {
        if ( strpos( $uri, $pattern ) !== false ) {
            echo '<meta name="robots" content="noindex, nofollow">' . "
";
            return; // Only output once
        }
    }
}

// =============================================================================
// PART 2: NOINDEX — PAST (EXPIRED) INDIVIDUAL EVENT PAGES
// =============================================================================
/**
 * Adds noindex, follow to individual event pages whose end date has passed.
 *
 * Why noindex and not noindex,nofollow?
 *   - noindex tells Google not to index the page
 *   - follow allows Google to still crawl links on the page
 *   - This preserves link equity from any internal links on the event page
 *
 * Upcoming and active events are NOT affected — they remain fully indexable.
 *
 * Requires: The Events Calendar plugin (tribe_get_end_date function)
 */
add_action( 'wp_head', 'ecss_noindex_past_events', 1 );

function ecss_noindex_past_events() {
    // Only run on single event pages
    if ( ! is_singular( 'tribe_events' ) ) return;

    // Check if The Events Calendar function exists
    if ( ! function_exists( 'tribe_get_end_date' ) ) return;

    // Get the event end date as a Unix timestamp
    $event_end = tribe_get_end_date( null, false, 'U' );

    // If the event has ended, add noindex
    if ( $event_end && $event_end < time() ) {
        echo '<meta name="robots" content="noindex, follow">' . "
";
    }
}

// =============================================================================
// PART 3: EVENT SCHEMA MARKUP (JSON-LD)
// =============================================================================
/**
 * Outputs structured data for single event pages in JSON-LD format.
 *
 * Schema.org Event type includes:
 *   - Event name, description, URL
 *   - Start and end date/time
 *   - Event image (featured image)
 *   - Venue name and full postal address
 *   - Event status and attendance mode
 *
 * This enables Google to show rich results for your events in search.
 *
 * -----------------------------------------------------------------------
 * CUSTOMIZATION OPTIONS:
 * -----------------------------------------------------------------------
 *
 * EVENT ATTENDANCE MODE — change the value below if your events are online:
 *   In-person:  https://schema.org/OfflineEventAttendanceMode
 *   Online:     https://schema.org/OnlineEventAttendanceMode
 *   Mixed:      https://schema.org/MixedEventAttendanceMode
 *
 * EVENT STATUS — change if you need to mark events as cancelled/postponed:
 *   Scheduled:  https://schema.org/EventScheduled
 *   Cancelled:  https://schema.org/EventCancelled
 *   Postponed:  https://schema.org/EventPostponed
 *   Rescheduled: https://schema.org/EventRescheduled
 * -----------------------------------------------------------------------
 *
 * Requires: The Events Calendar plugin
 * Compatible with: Yoast SEO, RankMath (does not conflict)
 */
add_action( 'wp_head', 'ecss_event_schema' );

function ecss_event_schema() {
    // Only run on single event pages
    if ( ! is_singular( 'tribe_events' ) ) return;

    // Check required Events Calendar functions exist
    if ( ! function_exists( 'tribe_get_start_date' ) || ! function_exists( 'tribe_get_end_date' ) ) return;

    global $post;

    // ── Core event details ─────────────────────────────────────────────
    $event_name        = get_the_title( $post->ID );
    $event_description = wp_strip_all_tags( get_the_excerpt( $post->ID ) );
    $event_url         = get_permalink( $post->ID );
    $event_start       = tribe_get_start_date( $post->ID, false, 'Y-m-d\TH:i:s' );
    $event_end         = tribe_get_end_date( $post->ID, false, 'Y-m-d\TH:i:s' );
    $event_image       = get_the_post_thumbnail_url( $post->ID, 'full' );

    // ── Venue details ──────────────────────────────────────────────────
    $venue_name    = function_exists( 'tribe_get_venue' )          ? tribe_get_venue( $post->ID )          : '';
    $venue_address = function_exists( 'tribe_get_address' )        ? tribe_get_address( $post->ID )        : '';
    $venue_city    = function_exists( 'tribe_get_city' )           ? tribe_get_city( $post->ID )           : '';
    $venue_state   = function_exists( 'tribe_get_stateprovince' )  ? tribe_get_stateprovince( $post->ID )  : '';
    $venue_zip     = function_exists( 'tribe_get_zip' )            ? tribe_get_zip( $post->ID )            : '';
    $venue_country = function_exists( 'tribe_get_country' )        ? tribe_get_country( $post->ID )        : '';

    // ── Build schema array ─────────────────────────────────────────────
    $schema = array(
        '@context'    => 'https://schema.org',
        '@type'       => 'Event',
        'name'        => esc_html( $event_name ),
        'description' => esc_html( $event_description ),
        'url'         => esc_url( $event_url ),
        'startDate'   => $event_start,
        'endDate'     => $event_end,

        // !! CHANGE THIS if your events are online or mixed !!
        'eventAttendanceMode' => 'https://schema.org/OfflineEventAttendanceMode',

        // !! CHANGE THIS if event is cancelled, postponed, or rescheduled !!
        'eventStatus' => 'https://schema.org/EventScheduled',
    );

    // Add image only if the event has a featured image
    if ( $event_image ) {
        $schema['image'] = esc_url( $event_image );
    }

    // Add venue/location only if a venue is set
    if ( $venue_name ) {
        $schema['location'] = array(
            '@type' => 'Place',
            'name'  => esc_html( $venue_name ),
            'address' => array(
                '@type'           => 'PostalAddress',
                'streetAddress'   => esc_html( $venue_address ),
                'addressLocality' => esc_html( $venue_city ),
                'addressRegion'   => esc_html( $venue_state ),
                'postalCode'      => esc_html( $venue_zip ),
                'addressCountry'  => esc_html( $venue_country ),
            ),
        );
    }

    // ── Output the schema as JSON-LD ───────────────────────────────────
    echo '<script type="application/ld+json">' . "
";
    echo wp_json_encode( $schema, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT );
    echo "
" . '</script>' . "
";
}
